from pathlib import Path
import pandas as pd
import streamlit as st
import plotly.express as px

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'outputs'

st.set_page_config(page_title='Credit Risk Dashboard', page_icon='💳', layout='wide')
st.title('💳 Credit Risk & Probability of Default Dashboard')
st.caption('UCI Default of Credit Card Clients — model outputs generated by the project pipeline')

metrics = pd.read_csv(OUT/'model_metrics.csv')
risk = pd.read_csv(OUT/'risk_summary.csv')
scores = pd.read_csv(OUT/'customer_risk_scores.csv')

c1,c2,c3,c4 = st.columns(4)
c1.metric('Customers', f"{len(scores):,}")
c2.metric('Observed default rate', f"{scores.default_flag.mean()*100:.2f}%")
c3.metric('Average predicted PD', f"{scores.predicted_pd.mean()*100:.2f}%")
c4.metric('Highest model ROC-AUC', f"{metrics.roc_auc.max():.3f}")

st.subheader('Model performance')
st.dataframe(metrics.style.format({'roc_auc':'{:.3f}','pr_auc':'{:.3f}','accuracy':'{:.3f}','precision':'{:.3f}','recall':'{:.3f}','f1':'{:.3f}'}), use_container_width=True)

left,right = st.columns(2)
with left:
    st.plotly_chart(px.bar(metrics, x='model', y='roc_auc', title='ROC-AUC by model'), use_container_width=True)
with right:
    st.plotly_chart(px.bar(risk, x='risk_band', y='customers', title='Customers by risk band'), use_container_width=True)

st.subheader('Risk-band monitoring')
st.plotly_chart(px.bar(risk, x='risk_band', y='actual_default_rate', title='Observed default rate by predicted risk band'), use_container_width=True)

st.subheader('Customer-level risk explorer')
min_pd, max_pd = st.slider('Predicted PD range', 0.0, 1.0, (0.0, 1.0), 0.01)
view = scores[scores.predicted_pd.between(min_pd,max_pd)].sort_values('predicted_pd', ascending=False)
st.dataframe(view.head(500), use_container_width=True)
